name = "bude-global-utils-api"
main = "src/main.py"
compatibility_date = "2026-01-16"
compatibility_flags = ["python_workers"]

# Development configuration
[env.dev]
workers_dev = true

# Production configuration  
[env.production]
workers_dev = false
